CREATE TABLE IF NOT EXISTS raw_training_data (
    front_id VARCHAR(20),
    sender VARCHAR(100),
    from_sender VARCHAR(100),
    subject VARCHAR(500),
    date DATE,
    receiver VARCHAR(100),
    body VARCHAR(4000),
    id_offer INT,
    important INT,
    notarization INT,
    id_poject INT,
    id_auto_request INT,
    id_customer VARCHAR(45),
    customer_type VARCHAR(15),
    requester_email VARCHAR(200),
    requester_name VARCHAR(50),
    requester_tel VARCHAR(30),
    lang VARCHAR(2),
    am VARCHAR(50),
    arrival_datetime DATE,
    am_fetch_datetime DATE,
    response_date DATE,
    target_response_date DATE,
    sys_response_date DATE,
    source_channel VARCHAR(15),
    fax_confirm_request INT,
    status VARCHAR(45),
    accept_refuse_datetime DATE,
    fax_confirm_date DATE,
    first_offer FLOAT,
    current_offer FLOAT ,
    accepted_offer FLOAT,
    assigned_to_pm VARCHAR(45),
    suggested_translator VARCHAR(30),
    id SERIAL PRIMARY KEY
);