CREATE TABLE IF NOT EXISTS raw_training_data (
    sender VARCHAR(100),
    subject VARCHAR(500),
    arrival_datetime DATE,
    body VARCHAR(4000),
    tag_list VARCHAR(200),
    id_front VARCHAR(15),
    id_offer INT,
    id_project INT,
    author_name VARCHAR(100),
    important INT,
    notarization INT,
    id_auto_request INT,
    id_customer VARCHAR(45),
    customer_type VARCHAR(15),
    requester_name VARCHAR(50),
    requester_tel VARCHAR(30),
    lang VARCHAR(2),
    am VARCHAR(50),
    am_fetch_datetime DATE,
    response_date DATE,
    target_response_date DATE,
    sys_response_date DATE,
    fax_confirm_request INT,
    fax_confirm_date DATE,
    first_offer FLOAT,
    current_offer FLOAT ,
    accepted_offer FLOAT,
    suggested_translator VARCHAR(30)
);

